const ActionName = {
  LOADING: "loading",
  SIGN_UP: "signUp",
  US_TIN_TYPE:"US_TIN_TYPE",
  COUNTRIES:"COUNTRIES",
  LANGUAGES:"LANGUAGE",

  //Page API's
  GET_ALL_PAGES: "GET_ALL_PAGES",
  DELETE_PAGE:"DELETE_PAGE",
  CREATE_PAGE:"CREATE_PAGE",
  PARENT_DROPDOWN:"PARENT_DROPDOWN",
  GET_ALL_CONTENT:"GET_ALL_CONTENT",
  GET_PAGE_BY_ID:"GET_PAGE_BY_ID",
  UPDATE_PAGE:"UPDATE_PAGE",

  // AGENTS API's
  GET_ALL_AGENTS:"GET_ALL_AGENTS",
  CREATE_AGENT:"CREATE_AGENT",
  DELETE_AGENT:"DELETE_AGENT"
};

export default ActionName;
